import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LayoutComponents } from "./components/bodyLayout/LayoutComponents";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const { Navbar, Footer } = LayoutComponents || {}
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black`}
      >
        <Navbar />
        <div className="xl:px-2 bg-black">
          <main className="min-h-[36rem] h-screen">
            {children}
          </main>
        </div>
        <Footer />


      </body>
    </html>
  );
}
